CREATE DATABASE BD_Universidad
GO

USE BD_Universidad
GO

CREATE TABLE Estados(
ID INT NOT NULL IDENTITY (1,1),
Nombre NVARCHAR (50)
CONSTRAINT PK_Estados PRIMARY KEY CLUSTERED (ID)
)


CREATE TABLE Niveles(
ID INT NOT NULL IDENTITY (1,1),
Nombre NVARCHAR (50) NOT NULL,
Numero INT NOT NULL
CONSTRAINT PK_Niveles PRIMARY KEY CLUSTERED (ID)
)

CREATE TABLE Estudiantes(
ID INT NOT NULL IDENTITY (1, 1),
Cedula NVARCHAR (50) NOT NULL,
Nombre NVARCHAR (50) NOT NULL,
Carnet INT,
Nivel INT NOT NULL,
CONSTRAINT PK_Estudiantes PRIMARY KEY CLUSTERED (ID),
CONSTRAINT FK_Niveles_Estudiantes FOREIGN KEY (Nivel) REFERENCES Niveles (ID) ON DELETE NO ACTION ON UPDATE NO ACTION 
)

CREATE TABLE Materias(
ID INT NOT NULL IDENTITY (1,1),
Nombre NVARCHAR (50) NOT NULL,
Creditos INT NOT NULL,
Nivel INT NOT NULL,
CONSTRAINT PK_Materias PRIMARY KEY CLUSTERED (ID),
CONSTRAINT FK_Niveles_Materias FOREIGN KEY (Nivel) REFERENCES Niveles (ID) ON DELETE NO ACTION ON UPDATE NO ACTION 
)

CREATE TABLE Salones (
ID INT NOT NULL IDENTITY (1,1),
Nombre NVARCHAR (50) NOT NULL,
Capacidad INT NOT NULL
CONSTRAINT PK_Salones PRIMARY KEY CLUSTERED (ID)
)

CREATE TABLE Clases_Estudiantes
(
ID INT NOT NULL IDENTITY (1,1),
Estudiante INT NOT NULL,
Materia INT NOT NULL,
Nota1 FLOAT NOT NULL,
Nota2 FLOAT NOT NULL,
Nota3 FLOAT NOT NULL,
Nota4 FLOAT NOT NULL,
Nota5 FLOAT NOT NULL,
CONSTRAINT PK_Clases_Estudiantes PRIMARY KEY CLUSTERED (ID),
CONSTRAINT FK_Estudiantes_Clases_Estudiantes FOREIGN KEY (Estudiante) REFERENCES Estudiantes (ID) ON DELETE NO ACTION ON UPDATE NO ACTION, 
CONSTRAINT FK_Materias_Clases_Estudiantes FOREIGN KEY (Materia) REFERENCES Materias (ID) ON DELETE NO ACTION ON UPDATE NO ACTION 
);